Port XEmacs 21.4 to AmigaOS 4 (PPC) - TTY console mode
Add AmigaOS 4 as a cross-compilation target using GCC 11 (newlib).
This provides a fully interactive TTY/console mode with:
- Working display via built-in termcap (amiga terminal entry)
- Keyboard input via WaitForChar() replacing select() on console fds
- 8-bit CSI (0x9B) translation for arrow/function keys
- AmigaOS absolute path recognition (Volume:path)
- POSIX stubs for missing functions (fork, pipe, wait3, etc.)
- Full Lisp bootstrap (all ~70 .elc files loaded from disk)
- PATH sanitization to filter non-AmigaOS paths

Build: CC=ppc-amigaos-gcc ./configure ppc-unknown-amigaos --without-x --with-tty=yes
Target: ELF 32-bit MSB PowerPC, ~2.3MB stripped

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1141,6 +1141,7 @@ case "$canonical" in
   romp-ibm-*       ) machine=ibmrt ;;
   rs6000-ibm-aix*  ) machine=ibmrs6000 ;;
   powerpc-ibm-aix* ) machine=ibmrs6000 ;;
+  ppc*-*-amigaos* | powerpc*-*-amigaos* ) machine=powerpc opsys=amigaos4 ;;
   powerpc*-*       ) machine=powerpc ;;
   hppa-*-*         ) machine=hp800 ;;
   m88k-dg-*        ) machine=aviion ;;
@@ -1559,7 +1560,7 @@ fi
 
 if test -z "$pdump"; then
   case "$opsys" in
-    linux* )  pdump=yes ;;        darwin )  pdump=yes ;;        cygwin* ) pdump=yes ;;        *)        pdump=no ;;
+    linux* )  pdump=yes ;;        darwin )  pdump=yes ;;        cygwin* ) pdump=yes ;;        amigaos4 ) pdump=yes ;;        *)        pdump=no ;;
   esac
 fi
 
@@ -4576,6 +4577,55 @@ fi
 echo $ac_n "checking whether byte ordering is bigendian""... $ac_c" 1>&6
 echo "configure:4578: checking whether byte ordering is bigendian" >&5
 
+if test "$opsys" = "amigaos4"; then
+  # Cross-compilation: PPC is big-endian, pre-set all sizes
+  ac_cv_c_bigendian=yes
+  echo "$ac_t""$ac_cv_c_bigendian (preset for cross-compilation)" 1>&6
+  { test "$extra_verbose" = "yes" && cat << \EOF
+    Defining WORDS_BIGENDIAN
+EOF
+cat >> confdefs.h <<\EOF
+#define WORDS_BIGENDIAN 1
+EOF
+}
+
+  ac_cv_sizeof_short=2
+  echo "checking size of short... $ac_cv_sizeof_short (preset)" 1>&6
+  { cat >> confdefs.h <<EOF
+#define SIZEOF_SHORT $ac_cv_sizeof_short
+EOF
+}
+
+  ac_cv_sizeof_int=4
+  echo "checking size of int... $ac_cv_sizeof_int (preset)" 1>&6
+  { cat >> confdefs.h <<EOF
+#define SIZEOF_INT $ac_cv_sizeof_int
+EOF
+}
+
+  ac_cv_sizeof_long=4
+  echo "checking size of long... $ac_cv_sizeof_long (preset)" 1>&6
+  { cat >> confdefs.h <<EOF
+#define SIZEOF_LONG $ac_cv_sizeof_long
+EOF
+}
+
+  ac_cv_sizeof_long_long=8
+  echo "checking size of long long... $ac_cv_sizeof_long_long (preset)" 1>&6
+  { cat >> confdefs.h <<EOF
+#define SIZEOF_LONG_LONG $ac_cv_sizeof_long_long
+EOF
+}
+
+  ac_cv_sizeof_void_p=4
+  echo "checking size of void *... $ac_cv_sizeof_void_p (preset)" 1>&6
+  { cat >> confdefs.h <<EOF
+#define SIZEOF_VOID_P $ac_cv_sizeof_void_p
+EOF
+}
+
+else
+
 ac_cv_c_bigendian=unknown
 # See if sys/param.h defines the BYTE_ORDER macro.
 cat > conftest.$ac_ext <<EOF
@@ -4852,6 +4902,7 @@ EOF
 }
 
 
+fi # end of amigaos4 cross-compilation preset
 
 case $opsys in
   cygwin* ) cat > conftest.$ac_ext <<EOF
@@ -16109,7 +16160,19 @@ cat > conftest.$ac_ext <<EOF
 #include "confdefs.h"
 int main(int c,char *v[]){return 0;}
 EOF
-if { (eval echo configure:16113: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit $?) 2>&5
+if test "$opsys" = "amigaos4"; then
+  # Cross-compilation: just check that it compiles and links
+  if { (eval echo configure:16113: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+    :
+  else
+    conftest_rc="$?"
+    echo "configure: failed program was:" >&5
+    cat conftest.$ac_ext >&5
+    rm -fr conftest*
+    echo "*** Cross-compilation link test failed. Check config.log."
+    exit 1
+  fi
+elif { (eval echo configure:16113: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit $?) 2>&5
 then
   :
 else
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1093,6 +1093,7 @@ case "$canonical" in
   romp-ibm-*       ) machine=ibmrt ;;
   rs6000-ibm-aix*  ) machine=ibmrs6000 ;;
   powerpc-ibm-aix* ) machine=ibmrs6000 ;;
+  ppc*-*-amigaos* | powerpc*-*-amigaos* ) machine=powerpc opsys=amigaos4 ;;
   powerpc*-*       ) machine=powerpc ;;
   hppa-*-*         ) machine=hp800 ;;
   m88k-dg-*        ) machine=aviion ;;
@@ -1589,10 +1590,11 @@ dnl --------------------------------------------------------------
 
 if test -z "$pdump"; then
   case "$opsys" in
-    linux* )  pdump=yes ;;    dnl glibc 2.3.1 seems to hose unexec
-    darwin )  pdump=yes ;;    dnl No "native" working dumper available
-    cygwin* ) pdump=yes ;;    dnl unexec is broken
-    *)        pdump=no ;;
+    linux* )     pdump=yes ;;    dnl glibc 2.3.1 seems to hose unexec
+    darwin )     pdump=yes ;;    dnl No "native" working dumper available
+    cygwin* )    pdump=yes ;;    dnl unexec is broken
+    amigaos4 )   pdump=yes ;;    dnl No unexec support on AmigaOS 4
+    *)           pdump=no ;;
   esac
 fi
 
@@ -2530,20 +2532,40 @@ dnl check for Make feature
 AC_PROG_MAKE_SET
 
 dnl check byte order
-AC_C_BIGENDIAN
+dnl For cross-compilation targets, we must pre-set values that require
+dnl running test programs on the target.
+case "$opsys" in
+  amigaos4 )
+    ac_cv_c_bigendian=yes
+    AC_DEFINE(WORDS_BIGENDIAN)
+    ac_cv_sizeof_short=2
+    AC_DEFINE(SIZEOF_SHORT, 2)
+    ac_cv_sizeof_int=4
+    AC_DEFINE(SIZEOF_INT, 4)
+    ac_cv_sizeof_long=4
+    AC_DEFINE(SIZEOF_LONG, 4)
+    ac_cv_sizeof_long_long=8
+    AC_DEFINE(SIZEOF_LONG_LONG, 8)
+    ac_cv_sizeof_void_p=4
+    AC_DEFINE(SIZEOF_VOID_P, 4)
+    ;;
+  * )
+    AC_C_BIGENDIAN
 
-dnl define SIZEOF_TYPE
-AC_CHECK_SIZEOF(short)
-if test "$ac_cv_sizeof_short" = 0; then
-  echo ""
-  echo "*** PANIC *** Configure tests are not working - compiler is broken."
-  echo "*** PANIC *** Please examine config.log for compilation errors."
-  exit 1
-fi
-AC_CHECK_SIZEOF(int)
-AC_CHECK_SIZEOF(long)
-AC_CHECK_SIZEOF(long long)
-AC_CHECK_SIZEOF(void *)
+    dnl define SIZEOF_TYPE
+    AC_CHECK_SIZEOF(short)
+    if test "$ac_cv_sizeof_short" = 0; then
+      echo ""
+      echo "*** PANIC *** Configure tests are not working - compiler is broken."
+      echo "*** PANIC *** Please examine config.log for compilation errors."
+      exit 1
+    fi
+    AC_CHECK_SIZEOF(int)
+    AC_CHECK_SIZEOF(long)
+    AC_CHECK_SIZEOF(long long)
+    AC_CHECK_SIZEOF(void *)
+    ;;
+esac
 
 dnl Cygwin from 1003022 has intptr_t, uintptr_t in <cygwin/types.h>
 case $opsys in
